<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="12.5.0" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\UseCases\UseCases.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="AutoMapper">
        <HintPath>..\..\..\.nuget\packages\automapper\13.0.1\lib\net6.0\AutoMapper.dll</HintPath>
      </Reference>
      <Reference Include="FluentValidation">
        <HintPath>..\..\..\.nuget\packages\fluentvalidation\11.11.0\lib\net6.0\FluentValidation.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
