<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>4007ab3e-d508-43fc-a950-b223e5f7abbe</UserSecretsId>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.22" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.22">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NLog.Web.AspNetCore" Version="5.4.0" />
        <PackageReference Include="Quartz.AspNetCore" Version="3.13.1" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="7.2.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Controllers\Controllers.csproj" />
      <ProjectReference Include="..\FileSystem\FileSystem.csproj" />
      <ProjectReference Include="..\UseCases\UseCases.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Newtonsoft.Json">
        <HintPath>..\..\..\.nuget\packages\newtonsoft.json\13.0.3\lib\net6.0\Newtonsoft.Json.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <None Update="City.sql">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="images\" />
      <Folder Include="wwwroot\" />
    </ItemGroup>

    <Target Name="BuildFrontend" AfterTargets="Build">
        <Exec Command="npm install" WorkingDirectory="..\activity_seeker_vk" />
        <Exec Command="npm run build" WorkingDirectory="..\activity_seeker_vk" />
    </Target>
    
</Project>
