<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>4007ab3e-d508-43fc-a950-b223e5f7abbe</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
        <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="6.0.22" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.26">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="NLog.Web.AspNetCore" Version="5.4.0" />
        <PackageReference Include="Quartz.AspNetCore" Version="3.13.1" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="7.2.0" />
        <PackageReference Include="Telegram.Bot" Version="19.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Controllers\Controllers.csproj" />
      <ProjectReference Include="..\UseCases\UseCases.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Newtonsoft.Json">
        <HintPath>..\..\..\.nuget\packages\newtonsoft.json\13.0.3\lib\net6.0\Newtonsoft.Json.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <None Update="City.sql">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="wwwroot\" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\files\3wepz511.v52" />
      <_ContentIncludedByDefault Remove="wwwroot\files\3zimoohs.fwh" />
      <_ContentIncludedByDefault Remove="wwwroot\files\5utnm3oa.mt3" />
      <_ContentIncludedByDefault Remove="wwwroot\files\ActivityPeriodChapter" />
      <_ContentIncludedByDefault Remove="wwwroot\files\ActivityTypeChapter" />
      <_ContentIncludedByDefault Remove="wwwroot\files\axeuebe4.qco" />
      <_ContentIncludedByDefault Remove="wwwroot\files\e4c5bonq.u2y" />
      <_ContentIncludedByDefault Remove="wwwroot\files\frbvtzom.a3p" />
      <_ContentIncludedByDefault Remove="wwwroot\files\i0ihx2oo.b3r" />
      <_ContentIncludedByDefault Remove="wwwroot\files\j1exfng2.ndp" />
      <_ContentIncludedByDefault Remove="wwwroot\files\ListOfActivities" />
      <_ContentIncludedByDefault Remove="wwwroot\files\MainMenu" />
      <_ContentIncludedByDefault Remove="wwwroot\files\n2bzebkx.zef" />
      <_ContentIncludedByDefault Remove="wwwroot\files\Offer" />
      <_ContentIncludedByDefault Remove="wwwroot\files\pmyvy300.p3a" />
      <_ContentIncludedByDefault Remove="wwwroot\files\qk4leeey.scp" />
      <_ContentIncludedByDefault Remove="wwwroot\files\SaveDefaultSettings" />
      <_ContentIncludedByDefault Remove="wwwroot\files\SaveOfferDate" />
      <_ContentIncludedByDefault Remove="wwwroot\files\SaveOfferDescription" />
      <_ContentIncludedByDefault Remove="wwwroot\files\SaveOfferFormat" />
      <_ContentIncludedByDefault Remove="wwwroot\files\SelectActivityFormat" />
      <_ContentIncludedByDefault Remove="wwwroot\files\SelectOfferCity" />
      <_ContentIncludedByDefault Remove="wwwroot\files\syb5ened.uu3" />
      <_ContentIncludedByDefault Remove="wwwroot\files\wh4tlxoo.r00" />
      <_ContentIncludedByDefault Remove="wwwroot\files\zst03mmz.bgn" />
    </ItemGroup>

    <Target Name="BuildFrontend" AfterTargets="Build">
        <Exec Command="npm install" WorkingDirectory="..\activity_seeker_vk" />
        <Exec Command="npm run build" WorkingDirectory="..\activity_seeker_vk" />
    </Target>
    
</Project>
