# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Set up dependency caching for faster builds
      uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: install dotnet ef tool
      run: dotnet tool install dotnet-ef --global --version 6.*
      shell: bash

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o myapp

    - name: build dotnet ef migration bundle
      run: dotnet ef migrations bundle --self-contained --configuration Bundle -o myapp/efbundle --project ActivitySeeker.Api/ActivitySeeker.Api.csproj --verbose
      shell: bash

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: myapp

    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rlgoDzvc -i"
        SOURCE: "myapp/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: "/opt/activity_seeker"
        # EXCLUDE: "/dist/, /node_modules/"
        SCRIPT_BEFORE: |
          systemctl stop bot
        SCRIPT_AFTER: |
          cat >/opt/activity_seeker/appsettings.json <<EOT
          {
            "Logging": {
              "LogLevel": {
                "Default": "Information",
                "Microsoft.AspNetCore": "Warning"
              }
            },
            "AllowedHosts": "*",
            "BotConfiguration": {
              "BotToken": "${{ secrets.BOT_TOKEN }}",
              "WebhookUrl": "${{ secrets.WEBHOOK_URL }}",
              "TelegramChennel": "${{ secrets.TELEGRAM_CHENNEL }}",
              "PathToCertificate": "/etc/letsencrypt/live/v2575056.hosted-by-vdsina.ru/telegram_ssl_public.pem"
            },
            "ConnectionStrings": {
              "ActivitySeekerConnection": "${{ secrets.CONNECTION_STRING }}"
            },
            "JwtOptions": {
              "SecretKey": "${{ secrets.JWT_SECRET_KEY }}",
              "ExpiresHours": "12"
            }
          }
          EOT
          cd /opt/activity_seeker/
          /opt/activity_seeker/efbundle
          chown -R root:root /opt/activity_seeker/
          systemctl restart bot
